
name: Cypress Tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Use Chrome For Cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run cypress:run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true