name: Publish Tech Sandbox Join Store

on:
  pull_request:
   types: [closed]
   branches:
      dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli

    - name: Install Dependencies
      run: npm ci

    - name: Connect to store
      env:
        URL: ${{ secrets.STENCIL_STORE_URL_JOIN_TECH_SANDBOX }}
        TOKEN: ${{ secrets.STENCIL_ACCESS_TOKEN_JOIN_TECH_SANDBOX }}
      run: stencil init -u $URL -t $TOKEN -p 3000

    - name: Publishing theme to Tech-Sandbox Join Store, automatically deleting oldest theme if necessary
      run: stencil push -a Tech-Sandbox -d